name: freshcornersample
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  video_player: ^2.8.1
  shimmer: ^3.0.0
  pin_input_text_field: ^4.5.1
  carousel_slider: ^4.2.1
  image_picker: ^0.8.4+2
  image_picker_web: ^3.1.1
  curved_navigation_bar: ^1.0.3
  bottom_navy_bar: ^6.0.0
  flutter_svg: ^2.0.9
  neumorphic_ui: ^1.0.1
  neumorphic_button: ^0.0.1+2
  lottie: ^2.7.0
  glassmorphism: ^3.0.0
  cool_ui: ^1.3.0
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.1.0
  provider: ^6.1.1
  flutter_slidable: ^0.6.0
  google_fonts: ^6.1.0
  swipeable_button_view:
  page_transition: ^2.1.0
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: 'asset/image/719m4JpyUfL-removebg-preview.png'

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/
    - asset/icons/
    - asset/image/
    - asset/lottie/
    - asset/image/banner/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Bold.ttf
        - asset: asset/fonts/Poppins-Italic.ttf
        - asset: asset/fonts/Poppins-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
